name: tests

on:
  push:
    branches: [master]
  pull_request:

jobs:
  tests:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        php: ['8.3', '8.4']

    name: PHP ${{ matrix.php }} on ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      - run: composer install --no-interaction --no-progress --prefer-dist

      - run: vendor/bin/pint --test

      - run: vendor/bin/pest
